#!/bin/bash

outfiletemplate="${1}"
if [ "x${outfiletemplate}" == 'x' ]; then
    echo "Uso: ${0} <template de nome de arquivos>"
    exit 1
fi

echo 'Posicione o mouse no canto superior esquerdo da regiao para gravar.'
echo 'Em seguida, pressione <ENTER> para continuar.'
read
eval `xdotool getmouselocation --shell`
test "x${X}" != 'x' -a "y${Y}" != 'y' || exit 1
echo "Mouse esta em X=${X} ; Y=${Y}"
xtl="${X}"
ytl="${Y}"

echo ''
echo 'Agora, posicione o mouse no canto inferior direito da regiao para gravar.'
echo 'Em seguida, pressione <ENTER> para continuar.'
read
eval `xdotool getmouselocation --shell`
test "x${X}" != 'x' -a "y${Y}" != 'y' || exit 1
echo "Mouse esta em X=${X} ; Y=${Y}"
xbr="${X}"
ybr="${Y}"

echo 'Iniciando a gravacao com o "recordmydesktop".'
cachedir="${HOME}/.cache/recordmydesktop"
mkdir -p "${cachedir}" || exit 1
echo 'Envie CTRL+C para este script para interromper. Nao tecle CTRL+ALT+S'

keeepRecording='true'
trap 'keeepRecording="false"' INT TERM
recordPID=''
recordPIDS=''
oldRecordPID=''

for min in `seq -f %03g 1 999`; do
    oldRecordPID="${recordPID}"
    set -x
    recordmydesktop -x ${xtl} -y ${ytl} \
        --width $((xbr-xtl+1)) --height $((ybr-ytl+1)) \
        --no-cursor --fps 15 \
        --workdir "${cachedir}" \
        --device pulse \
        --overwrite -o "${outfiletemplate}.${min}.ogv" & recordPID=${!}
    set +x
    if [ "x${oldRecordPID}" != 'x' ]; then
        chrt -v -b -p 0 "${oldRecordPID}"
        renice 19 "${oldRecordPID}"
        ionice -c 3 -p "${oldRecordPID}"
    fi
    oldRecordPIDS="${recordPIDS}"
    recordPIDS="${recordPID}"
    for onePID in ${oldRecordPIDS}; do
        if [ "x${onePID}" != 'x' ]; then
            if [ -d "/proc/${onePID}" ]; then
                recordPIDS="${onePID} ${recordPIDS}"
            else
                wait "${onePID}"
            fi
        fi
    done
    for timer in `seq 1 300`; do
        sleep 1
        if "${keeepRecording}"; then
            if ! [ -d "/proc/${recordPID}" ]; then
                echo 'Gravador finalizou abruptamente, aparentemente...'
                wait "${recordPID}"
                recordPID=''
                break
            fi
            if ! [ "`stat -f -c '%a*%S/1024/1024/1024' \"${cachedir}\" | bc`" -ge 100 ]; then
                echo 'Pouco espaco em disco! Finalizando gravacao imediatamente...'
                keeepRecording='false'
                break
            fi
        else
            break
        fi
    done
    if [ "x${recordPID}" != 'x' ]; then
        kill -INT "${recordPID}"
    fi
    if ! "${keeepRecording}"; then
        break
    fi
done

chrt -v -b -p 0 "${recordPID}"
renice 19 "${recordPID}"
ionice -c 3 -p "${recordPID}"

echo 'Esperando os processos disparados em segundo plano...'
for recordPID in ${recordPIDS}; do
    wait "${recordPID}"
done

rmdir "${cachedir}"
