#!/bin/bash

echo 'Posicione o mouse no canto superior esquerdo da regiao para gravar.'
echo 'Em seguida, pressione <ENTER> para continuar.'
read
eval `xdotool getmouselocation --shell`
test "x${X}" != 'x' -a "y${Y}" != 'y' || exit 1
echo "Mouse esta em X=${X} ; Y=${Y}"
xtl="${X}"
ytl="${Y}"

echo ''
echo 'Agora, posicione o mouse no canto inferior direito da regiao para gravar.'
echo 'Em seguida, pressione <ENTER> para continuar.'
read
eval `xdotool getmouselocation --shell`
test "x${X}" != 'x' -a "y${Y}" != 'y' || exit 1
echo "Mouse esta em X=${X} ; Y=${Y}"
xbr="${X}"
ybr="${Y}"

echo 'Iniciando a gravacao com o "recordmydesktop".'
echo 'Use "Control+Alt+P" para pausar/reiniciar a gravacao.'
echo 'Use "Control+Alt+S" para finalizar a gravacao.'
echo "O arquivo de video gerado sera \"out.${$}.ogv\"."
echo ''

cachedir="${HOME}/.config/recordmydesktop"
mkdir -p "${cachedir}" || exit 1
set -x
recordmydesktop -x ${xtl} -y ${ytl} \
    --width $((xbr-xtl+1)) --height $((ybr-ytl+1)) \
    --no-cursor --fps 30 \
    --workdir "${cachedir}" \
    --device pulse \
    --overwrite -o "out.${$}.ogv" & recordPID=${!}
set +x

while [ -d "/proc/${recordPID}" ]; do
    sleep 1
    if ! [ "`stat -f -c '%a*%S/1024/1024/1024' \"${cachedir}\" | bc`" -ge 4 ]; then
        echo 'Pouco espaco em disco! Finalizando gravacao imediatamente...'
        kill -INT ${recordPID}
        break
    fi
done
wait ${recordPID}

rmdir "${cachedir}"
