#!/bin/bash

outfiletemplate="${1}"
if [ "x${outfiletemplate}" == 'x' ]; then
    echo "Uso: ${0} <template de nome de arquivos>"
    exit 1
fi

echo 'Posicione o mouse no canto superior esquerdo da regiao para gravar.'
echo 'Em seguida, pressione <ENTER> para continuar.'
read
eval `xdotool getmouselocation --shell`
test "x${X}" != 'x' -a "y${Y}" != 'y' || exit 1
echo "Mouse esta em X=${X} ; Y=${Y}"
xtl="${X}"
ytl="${Y}"

echo ''
echo 'Agora, posicione o mouse no canto inferior direito da regiao para gravar.'
echo 'Em seguida, pressione <ENTER> para continuar.'
read
eval `xdotool getmouselocation --shell`
test "x${X}" != 'x' -a "y${Y}" != 'y' || exit 1
echo "Mouse esta em X=${X} ; Y=${Y}"
xbr="${X}"
ybr="${Y}"

echo 'Iniciando a gravacao com o "recordmydesktop".'
cachedir="${HOME}/.cache/recordmydesktop"
mkdir -p "${cachedir}" || exit 1
echo 'Envie CTRL+C para este script para interromper. Nao tecle CTRL+ALT+S'

keeepRecording='true'
trap 'keeepRecording="false"' INT TERM
recordPIDS=''

for min in `seq -f %03g 1 999`; do
    set -x
    recordmydesktop -x ${xtl} -y ${ytl} \
        --width $((xbr-xtl+1)) --height $((ybr-ytl+1)) \
        --no-cursor --fps 30 \
        --workdir "${cachedir}" \
        --device pulse \
        --overwrite -o "${outfiletemplate}.${min}.ogv" & recordPID=${!}
    set +x
    recordPIDS="${recordPIDS} ${recordPID}"
    for timer in `seq 1 60`; do
        sleep 5
        if "${keeepRecording}"; then
            if ! [ "`stat -f -c '%a*%S/1024/1024/1024' \"${cachedir}\" | bc`" -ge 100 ]; then
                echo 'Pouco espaco em disco! Finalizando gravacao imediatamente...'
                keeepRecording='false'
                break
            fi
        else
            break
        fi
    done
    renice 19 "${recordPID}" & \
    ionice -c 3 -p "${recordPID}" & \
    kill -INT "${recordPID}"
    if ! "${keeepRecording}"; then
        break
    fi
done

trap '' INT TERM
echo 'Esperando os processos disparados em segundo plano...'
for recordPID in ${recordPIDS}; do
    wait "${recordPID}"
done

rmdir "${cachedir}"
